//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_table
    {
        public int ID { get; set; }
        public int id_number { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public byte[] status { get; set; }
    }
}
